name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Build binary with PyInstaller
      run: |
        source venv/bin/activate
        pip install pyinstaller
        pyinstaller --onefile main.py

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: password-manager
        path: dist/main

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download binary
      uses: actions/download-artifact@v2
      with:
        name: password-manager
        path: dist/

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
